name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.15
        lfs: true
    - name: install depedencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: twinning
        environment-file: environment.yml
        auto-activate-base: true
    - name: Checkout demo branch
      uses: actions/checkout@v3
      with:
        ref: gh_action
    - name: Build local package
      run: |
        python -m pip install .
    - name: Run pytest
      shell: bash -l {0}
      run: |
        git lfs pull
        unzip data/TheCompleteJourney.zip -d data/raw
        pytest tests