name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.15
    - name: install depedencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: twinning
        environment-file: environment.yml
        auto-activate-base: true
    - name: Lint
      shell: bash -l {0}
      run: |
        conda install flake8
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build local package
      run: |
        python -m pip install .
    - name: Run preprocess
      run: |
        preprocess
    - name: Run pytest
      shell: bash -l {0}
      run: |
        pytest -s
