name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.15
        lfs: true
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}
    - name: install depedencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: twinning
        environment-file: environment.yml
        auto-activate-base: true
    - name: Build local package
      run: |
        python -m pip install .
    - name: Run pytest
      shell: bash -l {0}
      run: |
        git lfs pull
        unzip data/TheCompleteJourney.zip -d data/raw
        pytest tests